-- Thread ACSet SQL Export
-- Generated: 2025-12-21 22:50:57

INSERT INTO thread_acset_objects VALUES ('T-019b4424-7b9e-7515-bb83-5514e2aefba8', 'Thread', '{"id": "T-019b4424-7b9e-7515-bb83-5514e2aefba8", "title": "Exploring relational thinking with HyJAX skills", "message_count": 36, "created": 1766375457.244321}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('T-019b4412-7cbf-705c-81e8-1b84fb6d49c3', 'Thread', '{"id": "T-019b4412-7cbf-705c-81e8-1b84fb6d49c3", "title": "Use alife skill with Exa MCP for refined queries", "message_count": 59, "created": 1766375457.244784}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('T-019b43f1-cae1-7043-9196-c6839793df4c', 'Thread', '{"id": "T-019b43f1-cae1-7043-9196-c6839793df4c", "title": "List of active workspace threads", "message_count": 112, "created": 1766375457.244811}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('T-019b381e-cb1c-728e-973f-b8d2106767ed', 'Thread', '{"id": "T-019b381e-cb1c-728e-973f-b8d2106767ed", "title": "DiscoPy interaction entropy harmonizer across 17 subagents", "message_count": 175, "created": 1766375457.244837}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('T-019b43de-907c-7008-a545-57e8ff698498', 'Thread', '{"id": "T-019b43de-907c-7008-a545-57e8ff698498", "title": "Random walk spectral gap refinement process", "message_count": 104, "created": 1766375457.244863}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:HyJAX', 'Concept', '{"name": "HyJAX", "frequency": 2}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:entropy', 'Concept', '{"name": "entropy", "frequency": 3}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:ColoredShape', 'Concept', '{"name": "ColoredShape", "frequency": 1}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:bidirectional', 'Concept', '{"name": "bidirectional", "frequency": 1}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:relational', 'Concept', '{"name": "relational", "frequency": 2}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:category', 'Concept', '{"name": "category", "frequency": 2}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:ACSet', 'Concept', '{"name": "ACSet", "frequency": 3}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:operad', 'Concept', '{"name": "operad", "frequency": 2}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:DuckDB', 'Concept', '{"name": "DuckDB", "frequency": 1}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:thread', 'Concept', '{"name": "thread", "frequency": 1}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:JAX', 'Concept', '{"name": "JAX", "frequency": 1}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:pullback', 'Concept', '{"name": "pullback", "frequency": 1}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_objects VALUES ('concept:monadic', 'Concept', '{"name": "monadic", "frequency": 1}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('HyJAX→entropy', 'related', 'concept:HyJAX', 'concept:entropy', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('HyJAX→ColoredShape', 'related', 'concept:HyJAX', 'concept:ColoredShape', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('HyJAX→bidirectional', 'related', 'concept:HyJAX', 'concept:bidirectional', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('HyJAX→relational', 'related', 'concept:HyJAX', 'concept:relational', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('HyJAX→category', 'related', 'concept:HyJAX', 'concept:category', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('entropy→ColoredShape', 'related', 'concept:entropy', 'concept:ColoredShape', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('entropy→bidirectional', 'related', 'concept:entropy', 'concept:bidirectional', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('entropy→relational', 'related', 'concept:entropy', 'concept:relational', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('entropy→category', 'related', 'concept:entropy', 'concept:category', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ColoredShape→bidirectional', 'related', 'concept:ColoredShape', 'concept:bidirectional', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ColoredShape→relational', 'related', 'concept:ColoredShape', 'concept:relational', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ColoredShape→category', 'related', 'concept:ColoredShape', 'concept:category', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('bidirectional→relational', 'related', 'concept:bidirectional', 'concept:relational', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('bidirectional→category', 'related', 'concept:bidirectional', 'concept:category', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('relational→category', 'related', 'concept:relational', 'concept:category', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ACSet→entropy', 'related', 'concept:ACSet', 'concept:entropy', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ACSet→operad', 'related', 'concept:ACSet', 'concept:operad', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ACSet→DuckDB', 'related', 'concept:ACSet', 'concept:DuckDB', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ACSet→thread', 'related', 'concept:ACSet', 'concept:thread', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ACSet→relational', 'related', 'concept:ACSet', 'concept:relational', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('operad→DuckDB', 'related', 'concept:operad', 'concept:DuckDB', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('operad→thread', 'related', 'concept:operad', 'concept:thread', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('operad→relational', 'related', 'concept:operad', 'concept:relational', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('DuckDB→thread', 'related', 'concept:DuckDB', 'concept:thread', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('DuckDB→relational', 'related', 'concept:DuckDB', 'concept:relational', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('thread→relational', 'related', 'concept:thread', 'concept:relational', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('HyJAX→JAX', 'related', 'concept:HyJAX', 'concept:JAX', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('entropy→JAX', 'related', 'concept:entropy', 'concept:JAX', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ACSet→pullback', 'related', 'concept:ACSet', 'concept:pullback', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ACSet→monadic', 'related', 'concept:ACSet', 'concept:monadic', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('ACSet→category', 'related', 'concept:ACSet', 'concept:category', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('pullback→operad', 'related', 'concept:pullback', 'concept:operad', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('pullback→monadic', 'related', 'concept:pullback', 'concept:monadic', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('pullback→category', 'related', 'concept:pullback', 'concept:category', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('operad→monadic', 'related', 'concept:operad', 'concept:monadic', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('operad→category', 'related', 'concept:operad', 'concept:category', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);
INSERT INTO thread_acset_morphisms VALUES ('monadic→category', 'related', 'concept:monadic', 'concept:category', '{"type": "co-occurs"}', CURRENT_TIMESTAMP);