[package]
name = "ProofOfFrog"
version = "1.0.0"
authors = ["Plurigrid ASI"]

[addresses]
zubyul = "_"

[dev-addresses]
zubyul = "0xf206f206f206f206f206f206f206f206f206f206f206f206f206f206f206f206"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "mainnet" }
