[package]
name = "AbleMarkets"
version = "1.0.0"
authors = ["*Able Markets"]

[addresses]
able_markets = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
