#!/usr/bin/env python3
"""
Create 42 dynamical systems skills with GF(3) balanced trits.
"""

import os
from pathlib import Path

SKILLS = [
    ("initial-value-problem", "Initial Value Problem", "Existence and uniqueness of solutions to ODEs with initial conditions", -1),
    ("vector-field", "Vector Field", "Assignment of vectors to points in phase space defining dynamics", 0),
    ("flow", "Flow", "One-parameter group of diffeomorphisms generated by vector field", +1),
    ("trajectory", "Trajectory", "Path traced by solution through phase space", -1),
    ("equilibrium", "Equilibrium", "Fixed points where vector field vanishes", 0),
    ("stability", "Stability", "Qualitative behavior of solutions near equilibria", +1),
    ("jacobian", "Jacobian", "Matrix of partial derivatives for linearization", -1),
    ("linearization", "Linearization", "Local approximation of nonlinear dynamics", 0),
    ("eigenvalue-stability", "Eigenvalue Stability", "Stability classification via Jacobian eigenvalues", +1),
    ("invariant-set", "Invariant Set", "Sets preserved by the flow", -1),
    ("stable-manifold", "Stable Manifold", "Manifold of points converging to equilibrium", 0),
    ("unstable-manifold", "Unstable Manifold", "Manifold of points diverging from equilibrium", +1),
    ("center-manifold", "Center Manifold", "Invariant manifold tangent to center eigenspace", -1),
    ("parameter-dependent", "Parameter-dependent", "Systems varying with external parameters", 0),
    ("bifurcation", "Bifurcation", "Qualitative change in dynamics as parameters vary", +1),
    ("saddle-node", "Saddle-node", "Bifurcation creating/destroying equilibrium pair", -1),
    ("transcritical", "Transcritical", "Bifurcation exchanging stability between equilibria", 0),
    ("pitchfork", "Pitchfork", "Symmetric bifurcation with symmetry breaking", +1),
    ("hopf", "Hopf", "Bifurcation creating limit cycle from equilibrium", -1),
    ("limit-set", "Limit Set", "Asymptotic behavior of trajectories (ω/α-limit sets)", 0),
    ("attractor", "Attractor", "Invariant set attracting nearby trajectories", +1),
    ("repeller", "Repeller", "Invariant set repelling nearby trajectories", -1),
    ("periodic-orbit", "Periodic Orbit", "Closed trajectory in phase space", 0),
    ("chaotic-attractor", "Chaotic Attractor", "Strange attractor with sensitive dependence on initial conditions", +1),
    ("lyapunov-function", "Lyapunov Function", "Scalar function decreasing along trajectories", -1),
    ("lyapunov-stability", "Lyapunov Stability", "Stability via Lyapunov's direct method", 0),
    ("lasalle-invariance", "LaSalle Invariance", "Invariance principle for asymptotic stability", +1),
    ("structural-stability", "Structural Stability", "Robustness of qualitative dynamics under perturbation", -1),
    ("hyperbolicity", "Hyperbolicity", "No eigenvalues on imaginary axis (robust dynamics)", 0),
    ("dynamical-system-functor", "Dynamical System Functor", "Categorical structure of dynamical systems", +1),
    ("time-parameterization", "Time Parameterization", "Reparameterization of time in flows", -1),
    ("phase-space-transformation", "Phase Space Transformation", "Coordinate changes preserving dynamics", 0),
    ("semi-conjugacy", "Semi-conjugacy", "Surjective map intertwining two dynamical systems", +1),
    ("coupled-system", "Coupled System", "Interacting dynamical systems", -1),
    ("synchronization", "Synchronization", "Convergence to common trajectory in coupled systems", 0),
    ("phase-locking", "Phase Locking", "Fixed phase relationship in oscillators", +1),
    ("networked-system", "Networked System", "Dynamical systems on graphs", -1),
    ("consensus", "Consensus", "Agreement protocol in multi-agent systems", 0),
    ("kuramoto-model", "Kuramoto Model", "Coupled oscillators with sinusoidal coupling", +1),
    ("invariant-measure", "Invariant Measure", "Measure preserved by the flow", -1),
    ("ergodicity", "Ergodicity", "Time averages equal space averages", 0),
    ("birkhoff-average", "Birkhoff Average", "Time average of observable along trajectory", +1),
]

GEODESIC_BLOCK = """
## Non-Backtracking Geodesic Qualification

**Condition**: μ(n) ≠ 0 (Möbius squarefree)

This skill is qualified for non-backtracking geodesic traversal:

1. **Prime Path**: No state revisited in skill invocation chain
2. **Möbius Filter**: Composite paths (backtracking) cancel via μ-inversion
3. **GF(3) Conservation**: Trit sum ≡ 0 (mod 3) across skill triplets
4. **Spectral Gap**: Ramanujan bound λ₂ ≤ 2√(k-1) for k-regular expansion

```
Geodesic Invariant:
  ∀ path P: backtrack(P) = ∅ ⟹ μ(|P|) ≠ 0
  
Möbius Inversion:
  f(n) = Σ_{d|n} g(d) ⟹ g(n) = Σ_{d|n} μ(n/d) f(d)
```
"""

def trit_name(t):
    return {-1: "MINUS", 0: "ERGODIC", +1: "PLUS"}[t]

def create_skill(slug, title, desc, trit):
    skill_dir = Path(__file__).parent.parent / "skills" / slug
    skill_dir.mkdir(parents=True, exist_ok=True)
    
    content = f'''---
name: {slug}
description: {desc}
trit: {trit}
geodesic: true
moebius: "μ(n) ≠ 0"
---

# {title}

**Trit**: {trit} ({trit_name(trit)})
**Domain**: Dynamical Systems Theory
**Principle**: {desc}

## Overview

{title} is a fundamental concept in dynamical systems theory, providing tools for understanding the qualitative behavior of differential equations and flows on manifolds.

## Mathematical Definition

```
{title.upper().replace(" ", "_")}: Phase space × Time → Phase space
```

## Key Properties

1. **Local behavior**: Analysis near equilibria and invariant sets
2. **Global structure**: Long-term dynamics and limit sets  
3. **Bifurcations**: Parameter-dependent qualitative changes
4. **Stability**: Robustness under perturbation

## Integration with GF(3)

This skill participates in triadic composition:
- **Trit {trit}** ({trit_name(trit)}): {"Sources/generators" if trit == +1 else "Sinks/absorbers" if trit == -1 else "Neutral/ergodic"}
- **Conservation**: Σ trits ≡ 0 (mod 3) across skill triplets

## AlgebraicDynamics.jl Connection

```julia
using AlgebraicDynamics

# {title} as compositional dynamical system
# Implements oapply for resource-sharing machines
```

## Related Skills

- equilibrium (trit 0)
- stability (trit +1)  
- bifurcation (trit +1)
- attractor (trit +1)
- lyapunov-function (trit -1)

---

**Skill Name**: {slug}
**Type**: Dynamical Systems / {title}
**Trit**: {trit} ({trit_name(trit)})
**GF(3)**: Conserved in triplet composition
{GEODESIC_BLOCK}'''
    
    (skill_dir / "SKILL.md").write_text(content)
    return slug

def main():
    print(f"Creating {len(SKILLS)} dynamical systems skills...")
    
    # Verify GF(3) conservation
    total_trit = sum(s[3] for s in SKILLS)
    print(f"Total trit sum: {total_trit} ≡ {total_trit % 3} (mod 3)")
    
    for slug, title, desc, trit in SKILLS:
        create_skill(slug, title, desc, trit)
        print(f"✓ {slug} (trit={trit:+d})")
    
    print(f"\nCreated {len(SKILLS)} skills")
    print(f"GF(3) sum: {total_trit} ≡ {total_trit % 3} (mod 3)")

if __name__ == "__main__":
    main()
