source 'https://rubygems.org'

ruby '>= 3.0.0'

gem 'ruby-lsp', group: :development
gem 'rubocop', group: :development

# Core testing & BDD
gem 'cucumber', '~> 9.0'
gem 'rspec', '~> 3.12'
gem 'rspec-expectations', '~> 3.12'

# Music & Audio
gem 'sonic-pi-cli', '>= 0.2.0'

# Utilities
gem 'json', '~> 2.6'
gem 'bundler', '~> 2.0'

# NATS/Synadia messaging (cloud native pub/sub + JetStream)
gem 'nats-pure', '~> 2.4'

# Mathematical OCR with balanced ternary checkpoints
gem 'mathpix', '~> 0.1.2'
